name: Manual Deploy to Production

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message/reason'
        required: true
        default: 'QA approved - deploying to production'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Display deployment info
      run: |
        echo "=========================================="
        echo "Manual Deployment to Production"
        echo "=========================================="
        echo "Message: ${{ inputs.deploy_message }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Deploying from: test-repo/main"
        echo "Deploying to: prod-repo/main"
        echo "=========================================="

    - name: Deploy to prod-repo using PAT
      env:
        PAT_TOKEN: ${{ secrets.PROD_REPO_PAT }}
      run: |
        # Configure git globally
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

        # Clone prod-repo
        git clone https://oauth2:${PAT_TOKEN}@github.com/Ali-ISAA/prod-repo.git prod-repo-temp

        # Remove everything except .git and .github from prod-repo
        cd prod-repo-temp
        find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +

        # Copy all files from test-repo except .github and README.md
        cd ..
        rsync -av --exclude='.git' --exclude='.github' --exclude='README.md' --exclude='prod-repo-temp' . prod-repo-temp/

        # Commit and push changes
        cd prod-repo-temp
        git add -A
        git diff --staged --quiet || git commit -m "Deploy from test-repo: ${{ inputs.deploy_message }} (by ${{ github.actor }})"
        git push origin main

    - name: Deployment summary
      run: |
        echo "✅ Successfully deployed to prod-repo!"
        echo "Deployment message: ${{ inputs.deploy_message }}"
        echo "Triggered by: ${{ github.actor }}"
